FROM python:3.12.2-bookworm

LABEL authors="Lucifer DiotsLU"

# Allow statements and log messages to immediately appear in the logs
ENV PYTHONUNBUFFERED True
# copy local code to the container image
ENV APP_HOME /back-end
WORKDIR $APP_HOME

ENV HOST 0.0.0.0

COPY . ./

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Run the web service on container startup. Here we use the gunicorn 
# webserver. with one worker processs and 8 threads
# For environment with multiple CPU cores, increase the number of workers
# to be equal to the cores available
# Timeout is set to 0 to disable the timeout of the workers to allow Cloud Run to handle instance scaling.
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app